/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ValidateTask': EventHandler<never, never>
    'ReceiveTask': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'task.received'; data: never }>
  }
    
}