/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ValidateTask': EventHandler<never, { topic: 'task.validated'; data: never }>
    'UrgentTaskHandler': EventHandler<never, { topic: 'task.completed'; data: never }>
    'ReceiveTask': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'task.received'; data: never }>
    'NormalTaskHandler': EventHandler<never, { topic: 'task.completed'; data: never }>
    'CompletionLogger': EventHandler<never, never>
    'AIAgentDecision': EventHandler<never, { topic: 'task.urgent'; data: never } | { topic: 'task.normal'; data: never }>
  }
    
}